name: Docker compose deploy

on:
  push:
    branches:
      - 'main'

jobs:
  check_out:
    name: check out
    runs-on: [self-hosted, linux, x64]  
    steps:
     - uses: actions/checkout@v1
  docker_compose:
    name: docker compose
    needs: check_out
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Build the image
      run: sudo docker build -t panelais/docker .
    - name: Build the docker-compose
      run: sudo docker run -p 5000:5000 -v /home/Refactor/https/:/home -v /home/data/:/app/data -d panelais/docker
